### ISSUE TITLE
入力を取り消したときの挙動について

### ISSUE THREAD

**Issue by mimifuwacc** [AkaakuHub/tarouka#1]
## 概要

入力欄に一度入力し、全て取り消したあと、結果に「 ゙」が残ってしまっているが、これはバグですか？

![image](https://github.com/user-attachments/assets/4f4a5f37-7aca-449e-b67c-267a9eff5c9a)

**Comment by AkaakuHub** [comment]
確かに

**Comment by AkaakuHub** [comment]
solved
